#!/usr/bin/env npx tsx
/**
 * Seed the `content` table from the fixture library.
 *
 * Idempotent: deletes existing rows where source='library' and re-inserts.
 * Teacher-created content (source='teacher') is preserved.
 *
 * Run via:
 *   scripts/db.sh -f <(npx tsx scripts/seed-content.ts --emit-sql)
 *
 * Or to apply directly (uses SUPABASE_DB_URL from env):
 *   npx tsx scripts/seed-content.ts --apply
 *
 * Source: src/lib/fixtures/student.ts
 */

import {
  fixturePhonicsContent,
  fixtureSpellingContent,
  fixtureReadAloudPassages,
  fixtureWordMatchContent,
  fixtureClozeContent,
} from "../src/lib/fixtures/student";

interface Row {
  type: "wordlist" | "passage" | "word_match_set" | "cloze_sentence";
  title: string;
  body: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  metadata: Record<string, unknown>;
}

const rows: Row[] = [];

for (const set of fixturePhonicsContent) {
  rows.push({
    type: "wordlist",
    title: set.title,
    body: set.words.map((w) => w.word).join(" "),
    difficulty: set.difficulty,
    metadata: {
      legacy_id: set.id,
      intended_for: "phonics",
      words: set.words,
    },
  });
}

for (const set of fixtureSpellingContent) {
  rows.push({
    type: "wordlist",
    title: set.title,
    body: set.words.map((w) => w.word).join(" "),
    difficulty: set.difficulty,
    metadata: {
      legacy_id: set.id,
      intended_for: "spelling",
      words: set.words,
    },
  });
}

for (const passage of fixtureReadAloudPassages) {
  rows.push({
    type: "passage",
    title: passage.title,
    body: passage.text,
    difficulty: passage.difficulty,
    metadata: {
      legacy_id: passage.id,
    },
  });
}

for (const set of fixtureWordMatchContent) {
  rows.push({
    type: "word_match_set",
    title: set.title,
    body: set.rounds.map((r) => r.target).join(" "),
    difficulty: set.difficulty,
    metadata: {
      legacy_id: set.id,
      intended_for: "phonics",
      prompt_kind: set.promptKind,
      rounds: set.rounds,
    },
  });
}

for (const set of fixtureClozeContent) {
  rows.push({
    type: "cloze_sentence",
    title: set.title,
    body: set.sentences.map((s) => s.text.replace("___", s.answer)).join(" "),
    difficulty: set.difficulty,
    metadata: {
      legacy_id: set.id,
      intended_for: set.intendedFor,
      sentences: set.sentences,
    },
  });
}

// Generate SQL
const escape = (s: string) => s.replace(/'/g, "''");

let sql = `-- Auto-generated by scripts/seed-content.ts. Do not edit by hand.
-- Source: src/lib/fixtures/student.ts

begin;

-- Wipe library content (teacher content is preserved)
delete from content where source = 'library';

insert into content (type, title, body, difficulty, metadata, source) values\n`;

const valueRows = rows.map((r) => {
  const meta = JSON.stringify(r.metadata).replace(/'/g, "''");
  return `  ('${r.type}', '${escape(r.title)}', '${escape(r.body)}', '${r.difficulty}', '${meta}'::jsonb, 'library')`;
});

sql += valueRows.join(",\n");
sql += ";\n\n";
sql += `-- Verify\nselect difficulty, type, count(*) from content where source = 'library' group by 1, 2 order by 1, 2;\n\n`;
sql += `commit;\n`;

// Emit SQL to stdout. Pipe to psql via:
//   scripts/db.sh -f <(npx tsx scripts/seed-content.ts)
process.stdout.write(sql);
